// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIvGxKlP2UVVCKxjMTBQDWEZ0zXv91TTY',
    appId: '1:403744934583:web:dda0e2bc4773f7f2a01b32',
    messagingSenderId: '403744934583',
    projectId: 'it-afternoon-2024',
    authDomain: 'it-afternoon-2024.firebaseapp.com',
    storageBucket: 'it-afternoon-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGoYXjrEIjMsu4Acj6EWRJNz5eLqZLsg',
    appId: '1:403744934583:android:d299c710147da566a01b32',
    messagingSenderId: '403744934583',
    projectId: 'it-afternoon-2024',
    storageBucket: 'it-afternoon-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6k_LEnXPPnDDf_TH6HKqiEBt4H2VeDtw',
    appId: '1:403744934583:ios:dfbce42791fd3feea01b32',
    messagingSenderId: '403744934583',
    projectId: 'it-afternoon-2024',
    storageBucket: 'it-afternoon-2024.appspot.com',
    iosBundleId: 'com.example.morningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6k_LEnXPPnDDf_TH6HKqiEBt4H2VeDtw',
    appId: '1:403744934583:ios:dfbce42791fd3feea01b32',
    messagingSenderId: '403744934583',
    projectId: 'it-afternoon-2024',
    storageBucket: 'it-afternoon-2024.appspot.com',
    iosBundleId: 'com.example.morningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIvGxKlP2UVVCKxjMTBQDWEZ0zXv91TTY',
    appId: '1:403744934583:web:369da24f959e8687a01b32',
    messagingSenderId: '403744934583',
    projectId: 'it-afternoon-2024',
    authDomain: 'it-afternoon-2024.firebaseapp.com',
    storageBucket: 'it-afternoon-2024.appspot.com',
  );
}
